from pytest import param, mark
# BASE_URL = getenv('BASE_URL',"http://selenium1py.pythonanywhere.com/")
BASE_URL = "http://selenium1py.pythonanywhere.com/"
LOGIN_LINK_ID = "id='login_link'"

IMPLICIT_WAIT = 4
EXPLICIT_WAIT = 4
WINDOW_SIZE = ('1280', '1024')

LANGUAGES = [
    'ar',
    'ru',
    'ca',
    'cs',
    'da',
    'de',
    'en',
    'el',
    'es',
    'fi',
    'fr',
    'it',
    'ko',
    'nl',
    'pl',
    'pt',
    'pt-br',
    'ro',
    'ru',
    'sk',
    'uk',
    param('zh-hans', marks=mark.xfail)]

REGISTERED_USERS = (('xxx@mail.com', '159951357753'),
                    ('xxxx@mail.com', 'qwerty159951'))

PRODUCTS = [['the-shellcoders-handbook_209', "The shellcoder's handbook"],
            ['hacking-exposed-wireless_208', 'Hacking Exposed Wireless'],
            ['coders-at-work_207', 'Coders at Work'],
            ['visual-guide-to-lock-picking_206', 'Visual Guide to Lock Picking'],
            ['studyguide-for-counter-hack-reloaded_205', 'Studyguide for Counter Hack Reloaded'],
            ['gray-hat-hacking_204', 'Gray Hat Hacking'],
            ['the-girl-who-played-with-non-fire_203', 'The Girl Who Played with Non-Fire'],
            ['reversing_202', 'Reversing'],
            ['cyberpunk_201', 'Cyberpunk'],
            ['applied-cryptography_200', 'Applied cryptography'],
            ['the-girl-who-kicked-the-hornets-nest_199', "The Girl Who Kicked the Hornet's Nest"],
            ['hackers-delight_198', "Hacker's Delight"],
            ['google-hacking_197', 'Google Hacking'],
            ['silence-on-the-wire_196', 'Silence On The Wire'],
            ['hacking-work_195', 'Hacking Work'],
            ['the-girl-with-the-dragon-tattoo_194', 'The Girl with the Dragon Tattoo'],
            ['metasploit_193', 'Metasploit'],
            ['we-are-anonymous_192', 'We Are Anonymous'],
            ['social-engineering_191', 'Social Engineering'],
            ['the-cathedral-the-bazaar_190', 'The Cathedral & the Bazaar'],
            ['the-masters-of-deception_189', 'The Masters of Deception'],
            ['hacking-exposed-non-fifth-edition_188', 'Hacking Exposed Non-Fifth Edition'],
            ['the-art-of-deception_187', 'The Art of Deception'],
            ['kingpin_186', 'Kingpin'],
            ['hackers-painters_185', 'Hackers & painters'],
            ['hackers_184', 'Hackers'],
            ['the-hacker-crackdown_183', 'The Hacker Crackdown'],
            ['hacking_182', 'Hacking'],
            ['the-art-of-intrusion_181', 'The Art of Intrusion'],
            ['ghost-in-the-wires_180', 'Ghost in the Wires'],
            ['expert-c-programming_179', 'Expert C Programming'],
            ['u6df1u5165u6d45u51fa-java_178', '深入浅出 Java'],
            ['reviewing-java_177', 'Reviewing Java'],
            ['software-craftsmanship_176', 'Software craftsmanship'],
            ['refactoring-to-patterns_175', 'Refactoring to patterns'],
            ['specification-by-example_174', 'Specification by Example'],
            ['97-things-every-programmer-should-know_173', '97 Things Every Programmer Should Know'],
            ['thinking-forth_172', 'Thinking Forth'],
            ['genetic-programming_171', 'Genetic Programming'],
            ['the-goal_170', 'The Goal'],
            ['the-art-of-the-start_169', 'The Art Of The Start'],
            ['agile-retrospective_168', 'Agile Retrospective'],
            ['extreme-programming-explained_167', 'Extreme Programming Explained.'],
            ['scrum-and-xp-from-the-trenches_166', 'Scrum and XP from the Trenches'],
            ['fearless-change_165', 'Fearless Change'],
            ['manage-your-project-portfolio_164', 'Manage Your Project Portfolio'],
            ['implementing-lean-software-development_163', 'Implementing Lean Software Development'],
            ['bridging-the-communication-gap_162', 'Bridging the Communication Gap'],
            ['stl-tutorial-and-reference-guide_161', 'STL tutorial and reference guide'],
            ['c_160', 'C'],
            ['sams-teach-yourself-perl-in-24-hours_159', 'Sams teach yourself Perl in 24 hours'],
            ['essentials-of-programming-languages_158', 'Essentials of programming languages'],
            ['the-agile-samurai_157', 'The Agile Samurai'],
            ['the-algorithm-design-manual_156', 'The Algorithm Design Manual'],
            ['beginning-java-2-sdk-14-edition_155', 'Beginning Java 2 SDK 1.4 edition'],
            ['reviewing-c_154', 'Reviewing C++'],
            ['lean-from-the-trenches_153', 'Lean from the Trenches'],
            ['assembly-language_152', 'Assembly Language'],
            ['release-it_151', 'Release It!'],
            ['the-clean-coder_150', 'The Clean Coder'],
            ['slack_149', 'Slack'],
            ['library-resources-technical-services_148', 'Library Resources & Technical Services'],
            ['unix-network-programming-interprocess-communications_147', 'UNIX Network Programming: Interprocess communications'],
            ['accelerated-c_146', 'Accelerated C++'],
            ['sams-teach-yourself-mysql-in-24-hours_145', 'Sams teach yourself MySQL in 24 hours'],
            ['php-and-mysql-web-development_144', 'Php And Mysql Web Development'],
            ['sams-teach-yourself-javascript-in-24-hours_143', 'Sams Teach Yourself JavaScript in 24 Hours'],
            ['learning-ruby_142', 'Learning Ruby'],
            ['haskell_141', 'Haskell'],
            ['the-c-programming-language_140', 'The C++ programming language'],
            ['object-oriented-software-construction_139', 'Object-oriented software construction'],
            ['the-rspec-book_138', 'The Rspec Book'],
            ['elements-of-style_137', 'Elements of Style'],
            ['joel-on-software_136', 'Joel on Software'],
            ['introduction-to-the-theory-of-computation_135', 'Introduction To The Theory Of Computation'],
            ['advanced-programming-in-the-unix-environment_134', 'Advanced programming in the Unix environment'],
            ['learning-perl_133', 'Learning Perl'],
            ['agile-software-development_132', 'Agile software development'],
            ['xunit-test-patterns_131', 'Xunit Test Patterns'],
            ['agile-web-development-whit-rails_130', 'Agile Web Development Whit Rails'],
            ['algorithms_129', 'Algorithms'],
            ['effective-java_128', 'Effective Java'],
            ['programming-perl_127', 'Programming Perl'],
            ['ansi-common-lisp_126', 'ANSI Common Lisp'],
            ['ship-it_125', 'Ship it!'],
            ['test-driven-development_124', 'Test-Driven Development'],
            ['growing-object-oriented-software-guided-by-tests_123', 'Growing Object-Oriented Software, Guided by Tests'],
            ['unix-network-programming_122', 'UNIX Network Programming'],
            ['learning-python_121', 'Learning Python'],
            ['programming-ruby_120', 'Programming Ruby'],
            ['la-practica-de-la-programacion_119', 'La práctica de la programación'],
            ['how-to-design-programs_118', 'How to design programs'],
            ['working-effectively-with-legacy-code_117', 'Working Effectively With Legacy Code'],
            ['head-first-design-patterns_116', 'Head First Design Patterns'],
            ['little-lisper_115', 'Little LISPer'],
            ['real-world-haskell_114', 'Real World Haskell'],
            ['the-unix-programming-environment_113', 'The UNIX programming environment'],
            ['structure-and-interpretation-of-computer-programs_112', 'Structure and Interpretation of Computer Programs'],
            ['artificial-intelligence_111', 'Artificial Intelligence'],
            ['u0421u043eu0432u0440u0435u043cu0435u043du043du044bu0435-u043eu043fu0435u0440u0430u0446u0438u043eu043du043du044bu0435-u0441u0438u0441u0442u0435u043cu044b_110', 'Современные операционные системы'],
            ['compilers-principles-techniques-and-tools_109', 'Compilers, principles, techniques, and tools'],
            ['javascript-the-good-parts_108', 'JavaScript: The Good Parts'],
            ['the-c-programming-language_107', 'The C++ programming language'],
            ['clean-code_106', 'Clean Code'],
            ['code-complete-second-edition_105', 'Code Complete, Second Edition'],
            ['the-mythical-man-month_104', 'The mythical man-month'],
            ['the-art-of-computer-programming-sorting-and-searching_103', 'The Art of Computer Programming: Sorting and searching'],
            ['refactoring_102', 'Refactoring'],
            ['structure-and-interpretation-of-computer-programs_101', 'Structure and Interpretation of Computer Programs'],
            ['design-patterns_100', 'Design Patterns'],
            ['alfresco-3-web-services_99', 'Alfresco 3 Web Services'],
            ['the-c-programming-language_98', 'The C Programming Language'],
            ['ariel_97', 'Ariel'],
            ['adolescence-of-p-1-r_96', 'Adolescence of P-1 (R)'],
            ['the-city-and-the-stars_95', 'The City and the Stars'],
            ['me_94', 'Me'],
            ['the-big-u_93', 'The Big U'],
            ['pilgrimage-to-earth_92', 'Pilgrimage to Earth'],
            ['deathstalker_91', 'Deathstalker'],
            ['stand-on-zanzibar_90', 'Stand on Zanzibar'],
            ['the-age-of-the-pussyfoot_89', 'The age of the pussyfoot'],
            ['richard-yates_88', 'Richard Yates'],
            ['valentina_87', 'Valentina'],
            ['queen-of-angels_86', 'Queen of Angels'],
            ['look-to-windward_85', 'Look to Windward'],
            ['the-two-faces-of-tomorrow_84', 'The Two Faces of Tomorrow'],
            ['hard-questions_83', 'Hard Questions'],
            ['love_82', 'Love'],
            ['bugs_81', 'Bugs'],
            ['all-the-troubles-of-the-world_80', 'All the Troubles of the World'],
            ['march-of-the-machines_79', 'March Of The Machines'],
            ['this-perfect-day_78', 'This Perfect Day'],
            ['why-is-unit-142857-sad_77', 'Why Is Unit 142857 Sad?'],
            ['gurps-robots_76', 'Gurps Robots'],
            ['the-ai-war_75', 'The Ai War'],
            ['the-humanoids_74', 'The Humanoids'],
            ['rur-rossums-universal-robots_73', "R.U.R. (Rossum's Universal Robots)"],
            ['solo_72', 'Solo'],
            ['the-cuckoos-egg_71', "The Cuckoo's Egg"],
            ['weapon_70', 'Weapon'],
            ['computer-one_69', 'Computer One'],
            ['host_68', 'Host'],
            ['the-ware-tetralogy_67', 'The Ware Tetralogy'],
            ['the-hacker-and-the-ants_66', 'The Hacker and the Ants'],
            ['vulcans-hammer_65', "Vulcan's Hammer"],
            ['back-slash_64', 'Back Slash'],
            ['exegesis_63', 'Exegesis'],
            ['hack_62', 'Hack'],
            ['a-hymn-before-battle_61', 'A Hymn Before Battle'],
            ['star-wars-trilogy_60', 'Star Wars trilogy'],
            ['lingo_59', 'Lingo'],
            ['transmission_58', 'Transmission'],
            ['rainbows-end_57', 'Rainbows End'],
            ['ghostwritten_56', 'Ghostwritten'],
            ['the-adding-machine_55', 'The Adding Machine'],
            ['the-jesus-incident_54', 'The Jesus Incident'],
            ['destination-void_53', 'Destination Void'],
            ['slant_52', 'Slant'],
            ['excession_51', 'Excession'],
            ['foucaults-pendulum_50', "Foucault's Pendulum"],
            ['sherry-and-narcotics_49', 'Sherry and Narcotics'],
            ['galatea-22_48', 'Galatea 2.2'],
            ['the-turing-option_47', 'The Turing Option'],
            ['when-harlie-was-one_46', 'When Harlie was one'],
            ['i-have-no-mouth_45', 'I Have No Mouth'],
            ['enigma_44', 'Enigma'],
            ['feed_43', 'Feed'],
            ['digital-fortress_42', 'Digital Fortress'],
            ['a-terrace-on-the-tower-of-babel_41', 'A Terrace on the Tower of Babel'],
            ['www_40', 'WWW'],
            ['pattern-recognition_39', 'Pattern Recognition'],
            ['stieg-larssons-millennium-trilogy-bundle_38', "Stieg Larsson's Millennium Trilogy Bundle"],
            ['the-silicon-jungle_37', 'The Silicon Jungle'],
            ['robopocalypse_36', 'Robopocalypse'],
            ['the-shockwave-riders_35', 'The Shockwave Riders'],
            ['the-diamond-age_34', 'The diamond age'],
            ['count-zero_33', 'Count Zero'],
            ['the-machine-stops-dodo-press_32', 'The Machine Stops (Dodo Press)'],
            ['speaker-for-the-dead_31', 'Speaker for the Dead'],
            ['old-mans-war_30', "Old Man's War"],
            ['little-brother_29', 'Little Brother'],
            ['carts-top-200-adult-books-for-young-adults-two-decades-in-review_28', "Cart's Top 200 Adult Books for Young Adults: Two Decades in Review"],
            ['tron_27', 'Tron'],
            ['catch-22_26', 'Catch-22'],
            ['the-robot-novels_25', 'The Robot Novels'],
            ['freedom_24', 'Freedom'],
            ['microserfs_23', 'Microserfs'],
            ['the-difference-engine_22', 'The Difference Engine'],
            ['player-piano_21', 'Player Piano'],
            ['2001_20', '2001'],
            ['2001_19', '2001'],
            ['daemon_18', 'Daemon'],
            ['the-moon-is-a-harsh-mistress_17', 'The Moon is a Harsh Mistress'],
            ['i-robot_16', 'I, Robot'],
            ['the-hitchhikers-guide-to-the-galaxy_15', "The Hitchhiker's Guide to the Galaxy"],
            ['cryptonomicon_14', 'Cryptonomicon'],
            ['neuromancer_13', 'Neuromancer.'],
            ['snow-crash_12', 'Snow Crash'],
            ['django-t-shirt_8', 'Django T-shirt'],
            ['commandlinefu-t-shirt_5', 'commandlinefu T-shirt'],
            ['oscar-t-shirt_1', 'Oscar T-shirt']]
